"""empty message

Revision ID: f24e77ed0124
Revises: ae3192382f1a
Create Date: 2024-03-26 08:47:45.588971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24e77ed0124'
down_revision = 'ae3192382f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)

    # ### end Alembic commands ###
